version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=books'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=khoi'
    ports:
      - '5432:5432'