services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'TZ=Asia/Ho_Chi_Minh'
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'