spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.hibernate: ERROR
    dev.weebook.api: INFO
    sql: trace

app:
  keys:
    public-key: classpath:key/public-key.pem
    private-key: classpath:key/private-key.pem