spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
app:
  key:
    public-key: classpath:key/publickey.pem
    private-key: classpath:key/privatekey.pem